title: Electric Masquerade
description: >- # Descriptions can be multi-line
  A portfolio showcasing 3D printing, Blender animation, and game development projects.
author: Electric Masquerade
theme: minima